spring:
  application:
    name: softdesign
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:softdesign}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:softdesign}
    password: ${DB_PASSWORD:softdesign}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

app:
  votacao:
    duracao-padrao-minutos: 1
  user-info:
    base-url: https://user-info.herokuapp.com
